---
- name: Install Apache, set timezone to Africa/Lagos and serve a simple HTML page that displays content to clearly identify on all 3 EC2 instances.
  hosts: all
  gather_facts: false

  tasks:
    - name: Upgrade System
      apt: upgrade=dist update_cache=yes force=yes

    - name: Set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Install Apache Server
      apt:
        name: apache2
        state: present

    - name: Copy content to display on server
      shell: echo "<h1>Altschool third semester mini-project. This is my IP $(hostname -f)</h1>" > /var/www/html/index.html

      notify:
        - Restart apache2

  handlers:
    - name: Restart apache2
      service:
        state: restarted
        name: apache2
        daemon_reload: yes       